/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zmaj9
 */
public class PonudaZaIzraduSaStavkama extends javax.swing.JFrame {

    /**
     * Creates new form PonudaZaIzraduSaStavkama
     */
    public PonudaZaIzraduSaStavkama() {
        initComponents();
        prikaziSvePonude();
        prikaziBasSveStavkeJerZastoDaNe();
    }
    //
                public void prikaziSvePonude(){
        try{
            ResultSet rs = null;
            //INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            //select PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE from "PONUDA_ZA_IZRADU" VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')




            String upit = "select p1.ponudaid#,p1.DATUM, p1.PRIMALACPONUDE, p1.NAPOMENA, p1.ROK, p1.PLACANJE, p1.FRANKO, p1.OPCIJAPONUDE from ponuda_za_izradu p1 order by ponudaid#";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //
    public void prikaziSveStavkeNaOsnovuPonude(){
        try{
            ResultSet rs = null;
            //INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            //select PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE from "PONUDA_ZA_IZRADU" VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            String upit = "select * from Stavka_Ponude where PonudaID# = "+jTextField9.getText()+" order by Stavkaid#";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }            
    //
    public void prikaziBasSveStavkeJerZastoDaNe(){
        try{
            ResultSet rs = null;
            //INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            //select PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE from "PONUDA_ZA_IZRADU" VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            String upit = "select * from Stavka_Ponude";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }            
    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        unosPonuda = new javax.swing.JButton();
        izmenaPonuda = new javax.swing.JButton();
        brisanjePonuda = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ponuda za izradu");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        unosPonuda.setText("Unos");
        unosPonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosPonudaActionPerformed(evt);
            }
        });

        izmenaPonuda.setText("Izmena");
        izmenaPonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenaPonudaActionPerformed(evt);
            }
        });

        brisanjePonuda.setText("Brisanje");
        brisanjePonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjePonudaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Sifra ponude");

        jButton1.setText("Osvezi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Primalac ponude");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Napomena");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Rok");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Placanje");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Franko");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Opcija ponude");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton2.setText("Unesi stavku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Izmeni stavku");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Obrisi stavku");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Prikazi stavke");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Sifra ponude");

        jLabel10.setText("Redni broj stavke");

        jLabel11.setText("Kolicina");

        jLabel12.setText("Datum Isporuke");

        jLabel13.setText("Sifra proizvoda");

        jButton6.setText("Obrisi sve stavke");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(unosPonuda)
                        .addGap(10, 10, 10)
                        .addComponent(izmenaPonuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brisanjePonuda))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton5)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)
                        .addGap(253, 253, 253))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(unosPonuda)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(izmenaPonuda)
                                .addComponent(brisanjePonuda)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(31, 31, 31)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unosPonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosPonudaActionPerformed
        //
//INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "insert into ponuda_za_izradu (ponudaid#,DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) values( "+jTextField1.getText()+", TO_DATE('"+jTextField2.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'),'"+jTextField3.getText()+"','"+jTextField4.getText()+"', TO_DATE('"+jTextField5.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'),'"+jTextField6.getText()+"','"+jTextField7.getText()+"','"+jTextField8.getText()+"')";
                    int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is created");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not created");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
			try{
				if(con!=null){
					con.close();
					con=null;
                                                }
                            }
			catch (SQLException e){
				e.printStackTrace();
                                                } 
                        prikaziSvePonude();
// TODO add your handling code here:
        
    }//GEN-LAST:event_unosPonudaActionPerformed

    private void brisanjePonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjePonudaActionPerformed
        // TODO add your handling code here:
         try{
        String upit = "delete from ponuda_za_izradu where ponudaid# =" + Integer.parseInt(jTextField1.getText());
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSvePonude();
        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_brisanjePonudaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void izmenaPonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenaPonudaActionPerformed
        // TODO add your handling code here:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    /*String a1=jTextField1.getText();
                    String a2="TO_DATE('"+jTextField2.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS)";
                    String a3=jTextField3.getText();
                    String a4=jTextField4.getText();
                    String a5=jTextField5.getText();
                    String a6=jTextField6.getText();
                    String a7=jTextField7.getText();
                    String a8=jTextField8.getText();
                    */
                    String sql = "update ponuda_za_izradu set "
                            + "DATUM = TO_DATE('"+jTextField2.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'), "
                            + "PRIMALACPONUDE= '"+jTextField3.getText() + "',"
                            + "NAPOMENA= '"+jTextField4.getText()+ "',"
                            + "ROK= TO_DATE('"+jTextField5.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'),"
                            + "PLACANJE= '"+jTextField6.getText()+ "',"
                            + "FRANKO= '"+jTextField7.getText()+ "',"
                            + "OPCIJAPONUDE= '"+jTextField8.getText()+ "'"
                            + "where ponudaid# = "+jTextField1.getText();
                            String sql2 = "update ponuda_za_izradu set datum = ";
                    //gledaj da je sve malim slovima
                    String potvrdi = "Commit;";
					int i = stmt.executeUpdate(sql);
                                        stmt.executeUpdate(potvrdi);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is updated");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not updated");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
	catch (SQLException e){
		e.printStackTrace();
                                                }
	try{
	if(con!=null){
            con.close();
            con=null;
                      }
                            }
	catch (SQLException e){
				e.printStackTrace();
                                                }
prikaziSvePonude();
        //
    }//GEN-LAST:event_izmenaPonudaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        prikaziSvePonude();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        prikaziSveStavkeNaOsnovuPonude();
        //
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Uspesna insert naredba:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "INSERT INTO \"ZMAJ\".\"STAVKA_PONUDE\" (PONUDAID#, STAVKAID#, KOLICINA, DATUMISPORUKE, PROIZVODID#) VALUES"
                            + "( " + jTextField9.getText()+", "+jTextField10.getText()+", "+ jTextField11.getText()+ ", TO_DATE('"+jTextField12.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'), "+jTextField13.getText()+")";
                    int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is created");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not created");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
			try{
				if(con!=null){
					con.close();
					con=null;
                                                }
                            }
			catch (SQLException e){
				e.printStackTrace();
                                                }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "update Stavka_Ponude SET Kolicina = '"+jTextField11.getText() +"', DatumIsporuke= TO_DATE('"+jTextField12.getText()+" 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), ProizvodID#='"+jTextField13.getText()+"' where PonudaID# = '"+jTextField9.getText()+"' and StavkaID# = '"+jTextField10.getText()+"'";
                    //gledaj da je sve malim slovima
					int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is updated");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not updated");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
	catch (SQLException e){
		e.printStackTrace();
                                                }
	try{
	if(con!=null){
            con.close();
            con=null;
                      }
                            }
	catch (SQLException e){
				e.printStackTrace();
                                                }

        //
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                 try{
        String upit = "delete from stavka_ponude where ponudaid# = " + jTextField9.getText() + " and stavkaid# = "+jTextField10.getText();
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSvePonude();
        prikaziSveStavkeNaOsnovuPonude();

        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         // TODO add your handling code here:
                 try{
        String upit = "delete from stavka_ponude where ponudaid# = " + jTextField9.getText();
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSvePonude();
        prikaziSveStavkeNaOsnovuPonude();

        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_jButton6ActionPerformed
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PonudaZaIzraduSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PonudaZaIzraduSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PonudaZaIzraduSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PonudaZaIzraduSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PonudaZaIzraduSaStavkama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brisanjePonuda;
    private javax.swing.JButton izmenaPonuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton unosPonuda;
    // End of variables declaration//GEN-END:variables
}
