/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Forme.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zmaj9
 */
public class TenderSaStavkama extends javax.swing.JFrame {

    /**
     * Creates new form PonudaZaIzraduSaStavkama
     */
    public TenderSaStavkama() {
        initComponents();
        prikaziSveTender();
        prikaziBasSveStavkeJerZastoDaNe();
    }
    //
                public void prikaziSveTender(){
        try{
            ResultSet rs = null;
            String upit = "select * from tender order by tenderid#";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //
    public void prikaziSveStavkeNaOsnovuPonude(){
        try{
            ResultSet rs = null;
            //INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            //select PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE from "PONUDA_ZA_IZRADU" VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            String upit = "select * from Stavka_Tendera where TENDERID# = "+jTextField9.getText()+" order by Stavkaid#";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            //INSERT INTO "ZMAJ"."STAVKA_TENDERA" (TENDERID#, STAVKAID#, KRATKIOPIS, ZAHTEVANAKOLICINA, ZAHTEVANIDATUMISPORUKE, ZAHTEVANIOPIS, JEDMERE) VALUES ('1', '2', 'asd', '22', TO_DATE('2018-01-30 00:20:23', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'Kg')

            jTable2.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }            
    //
    public void prikaziBasSveStavkeJerZastoDaNe(){
        try{
            ResultSet rs = null;
            //INSERT INTO "ZMAJ"."PONUDA_ZA_IZRADU" (PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE) VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            //select PONUDAID#, DATUM, PRIMALACPONUDE, NAPOMENA, ROK, PLACANJE, FRANKO, OPCIJAPONUDE from "PONUDA_ZA_IZRADU" VALUES ('2', TO_DATE('2018-01-29 17:46:56', 'YYYY-MM-DD HH24:MI:SS'), 'Marko', 'Nema', TO_DATE('2018-01-24 17:47:07', 'YYYY-MM-DD HH24:MI:SS'), 'asd', 'dsa', 'asd')
            String upit = "select TENDERID#, STAVKAID#, KRATKIOPIS, ZAHTEVANAKOLICINA, ZAHTEVANIDATUMISPORUKE, ZAHTEVANIOPIS, JEDMERE from Stavka_TENDERA order by TenderID# asc, stavkaid# asc";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }            
    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        unosPonuda = new javax.swing.JButton();
        izmenaPonuda = new javax.swing.JButton();
        brisanjePonuda = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tender");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        unosPonuda.setText("Unos");
        unosPonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosPonudaActionPerformed(evt);
            }
        });

        izmenaPonuda.setText("Izmena");
        izmenaPonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenaPonudaActionPerformed(evt);
            }
        });

        brisanjePonuda.setText("Brisanje");
        brisanjePonuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjePonudaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Sifra Tendera");

        jButton1.setText("Osvezi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Unesi stavku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Izmeni stavku");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Obrisi stavku");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Prikazi stavke");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Sifra Tendera");

        jLabel10.setText("Redni broj stavke");

        jLabel11.setText("Kratki Opis");

        jLabel12.setText("Zahtevana kolicina");

        jLabel13.setText("Zahtevani datum isporuke");

        jLabel14.setText("Zahtevani opis");

        jLabel15.setText("Jedinica mere");

        jButton6.setText("Obrisi sve stavke");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(unosPonuda)
                        .addGap(10, 10, 10)
                        .addComponent(izmenaPonuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brisanjePonuda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(unosPonuda)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(izmenaPonuda)
                                .addComponent(brisanjePonuda)))))
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton6)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unosPonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosPonudaActionPerformed
        //
try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "insert into tender (tenderid#,DATUM) values ("+jTextField1.getText()+", TO_DATE('"+jTextField2.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'))";
                    //String sql = "insert into tender (tenderid#,DATUM,) values (2, TO_DATE('dat 12:00:00','YYYY-MM-DD HH24:MI:SS'))";
                    int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is created");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not created");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
			try{
				if(con!=null){
					con.close();
					con=null;
                                                }
                            }
			catch (SQLException e){
				e.printStackTrace();
                                                } 
                        prikaziSveTender();
// TODO add your handling code here:
        
    }//GEN-LAST:event_unosPonudaActionPerformed

    private void brisanjePonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjePonudaActionPerformed
        // TODO add your handling code here:
         try{
        String upit = "delete from TENDER where TENDERID# =" + Integer.parseInt(jTextField1.getText());
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSveTender();
        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_brisanjePonudaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void izmenaPonudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenaPonudaActionPerformed
        // TODO add your handling code here:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    /*String a1=jTextField1.getText();
                    String a2="TO_DATE('"+jTextField2.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS)";
                    String a3=jTextField3.getText();
                    String a4=jTextField4.getText();
                    String a5=jTextField5.getText();
                    String a6=jTextField6.getText();
                    String a7=jTextField7.getText();
                    String a8=jTextField8.getText();
                    */
                    
                    String sql ="UPDATE TENDER SET DATUM = TO_DATE('"+jTextField2.getText()+" 12:00:00', 'YYYY-MM-DD HH24:MI:SS') WHERE TENDERID# =" + jTextField1.getText();
                    //gledaj da je sve malim slovima
					int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is updated");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not updated");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
	catch (SQLException e){
		e.printStackTrace();
                                                }
	try{
	if(con!=null){
            con.close();
            con=null;
                      }
                            }
	catch (SQLException e){
				e.printStackTrace();
                                                }
prikaziSveTender();
        //
    }//GEN-LAST:event_izmenaPonudaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        prikaziSveTender();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        prikaziSveStavkeNaOsnovuPonude();
        //
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Uspesna insert naredba:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "INSERT INTO STAVKA_TENDERA VALUES('"+ jTextField9.getText()+ "', '"+jTextField10.getText()+ "', '"+jTextField11.getText()+ "', '"+jTextField12.getText()+ "', TO_DATE('"+jTextField13.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'), '"+jTextField14.getText()+ "', '"+jTextField15.getText()+"')";
                    int i = stmt.executeUpdate(sql); //TO_DATE('"+jTextField13.getText()+" 12:00:00','YYYY-MM-DD HH24:MI:SS'))
prikaziSveStavkeNaOsnovuPonude();
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is created");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not created");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
			try{
				if(con!=null){
					con.close();
					con=null;
                                                }
                            }
			catch (SQLException e){
				e.printStackTrace();
                                                }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "update Stavka_TENDERA SET KRATKIOPIS = '"+jTextField11.getText() +"', ZAHTEVANAKOLICINA = '"+jTextField12.getText()+"',  ZAHTEVANIDATUMISPORUKE= TO_DATE('"+jTextField13.getText()+" 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), ZAHTEVANIOPIS='"+jTextField14.getText()+"', JEDMERE='"+jTextField15.getText()+"' where TENDERID# = '"+jTextField9.getText()+"' and StavkaID# = '"+jTextField10.getText()+"'";
                    prikaziSveStavkeNaOsnovuPonude();
//(TENDERID#, STAVKAID#, KRATKIOPIS, ZAHTEVANAKOLICINA, ZAHTEVANIDATUMISPORUKE, ZAHTEVANIOPIS, JEDMERE
					int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is updated");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not updated");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
	catch (SQLException e){
		e.printStackTrace();
                                                }
	try{
	if(con!=null){
            con.close();
            con=null;
                      }
                            }
	catch (SQLException e){
				e.printStackTrace();
                                                }

        //
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                 try{
        String upit = "delete from stavka_tendera where tenderid# = " + jTextField9.getText() + " and stavkaid# = "+jTextField10.getText();
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSveTender();
        prikaziSveStavkeNaOsnovuPonude();

        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
                 try{
        String upit = "delete from stavka_tendera where tenderid# = " + jTextField9.getText();
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSveTender();
        prikaziSveStavkeNaOsnovuPonude();

        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_jButton6ActionPerformed
//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenderSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenderSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenderSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenderSaStavkama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenderSaStavkama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brisanjePonuda;
    private javax.swing.JButton izmenaPonuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton unosPonuda;
    // End of variables declaration//GEN-END:variables
}
