/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnosDodatnihPodataka;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zmaj9
 */
public class Porucilac extends javax.swing.JFrame {

    /**
     * Creates new form Porucilac
     */
    public Porucilac() {
        initComponents();
        prikaziSve();

    }
    public void prikaziSve(){
        try{
            ResultSet rs = null;
            String upit = "select p.porucilacid#, p.nazivporucioca, p.PIB.tip from porucilac p order by porucilacid#";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
            PreparedStatement ps = konekcija.prepareStatement(upit);
            rs = ps.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unesi = new javax.swing.JButton();
        Izmeni = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Porucilac");

        Unesi.setText("Unesi");
        Unesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnesiActionPerformed(evt);
            }
        });

        Izmeni.setText("Izmeni");
        Izmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmeniActionPerformed(evt);
            }
        });

        Obrisi.setText("Obrisi");
        Obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Sifra Porucilac");

        jLabel2.setText("Naziv");

        jLabel3.setText("PIB");

        jButton1.setText("Osvezi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Unesi)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Izmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Obrisi)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(0, 116, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unesi)
                    .addComponent(Izmeni)
                    .addComponent(Obrisi)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnesiActionPerformed
//
        try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "INSERT INTO PORUCILAC (PORUCILACID#, NAZIVPORUCIOCA, PIB) VALUES"
                            + "("+Integer.parseInt(jTextField1.getText())+", '"+jTextField2.getText()+"' , PIB('"+jTextField3.getText()+"'))";
                    int i = stmt.executeUpdate(sql);
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is created");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not created");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
			try{
				if(con!=null){
					con.close();
					con=null;
                                                }
                            }
			catch (SQLException e){
				e.printStackTrace();
                                                }
prikaziSve();
//
    }//GEN-LAST:event_UnesiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
prikaziSve();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmeniActionPerformed
//
try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
            }
	catch (ClassNotFoundException e){
                        JOptionPane.showMessageDialog(null, "Greska u loadovanju drajvera");
                }
                
                Connection con = null;
                Statement stmt = null;
               
        try{      
                    String URL = "jdbc:oracle:thin:@localhost:1521:xe";
                    String username = "zmaj";
                    String password = "root";
                    
                    con = DriverManager.getConnection(URL, username, password);
                    stmt = con.createStatement();
                    String sql = "update porucilac p SET p.nazivporucioca= '"+jTextField2.getText() +"', p.PIB.tip ='"+jTextField3.getText()+"' where p.PorucilacID# ="+ jTextField1.getText();
                    String sql2 = "update porucilac p set p.nazivporucioca= '"+jTextField2.getText() +"', p.PIB.tip ='"+jTextField3.getText()+"' where p.porucilacid# ="+ jTextField1.getText();
                    
                   
                    int i = stmt.executeUpdate(sql);
                    
                                
                    if(i > 0){
                        JOptionPane.showMessageDialog(null, "Row is updated");
			}
			else{
			JOptionPane.showMessageDialog(null, "Row is not updated");
			}
                }
        catch(Exception e){
                    e.printStackTrace();
                }
        try{
                    if(stmt!=null){
			stmt.close();
			stmt=null;
				}
            }
	catch (SQLException e){
		e.printStackTrace();
                                                }
	try{
	if(con!=null){
            con.close();
            con=null;
                      }
                            }
	catch (SQLException e){
				e.printStackTrace();
                                                }
        prikaziSve();

//
    }//GEN-LAST:event_IzmeniActionPerformed

    private void ObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiActionPerformed
        // TODO add your handling code here:
                try{
        String upit = "delete from porucilac where porucilacID# =" + Integer.parseInt(jTextField1.getText());
        //jTextField2.setText(null);
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection konekcija = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "zmaj", "root");
        PreparedStatement ps = konekcija.prepareStatement(upit);
        ps.execute();
        ps.close();
        konekcija.close();
        prikaziSve();
        }
    catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
        }
        //
    }//GEN-LAST:event_ObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Porucilac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Porucilac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Porucilac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Porucilac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Porucilac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Izmeni;
    private javax.swing.JButton Obrisi;
    private javax.swing.JButton Unesi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
